 export const ADD_ROW = 'ADD_ROW';
 export const ADD_ELEMENT = 'ADD_ELEMENT';
 export const ADD_COLUMN_INDEX = 'ADD_COLUMN_INDEX';
 export const ADD_ROW_INDEX = 'ADD_ROW_INDEX';
 export const ADD_SECTION_INDEX = 'ADD_SECTION_INDEX';
 export const ADD_SECTION = 'ADD_SECTION';
 export const UPDATE_ELEMENT_VALUE = 'UPDATE_ELEMENT_VALUE';
 export const ADD_ELEMENT_INDEX = 'ADD_ELEMENT_INDEX';