 export const OPEN_ROW_WIDGET = 'OPEN_ROW_WIDGET';
 export const CLOSE_ROW_WIDGET = 'CLOSE_ROW_WIDGET';
 export const OPEN_ELEMENT_WIDGET = 'OPEN_ELEMENT_WIDGET';
 export const CLOSE_ELEMENT_WIDGET = 'CLOSE_ELEMENT_WIDGET';
 export const OPEN_HEADLINE_EDITOR = 'OPEN_HEADLINE_EDITOR';
 export const CLOSE_HEADLINE_EDITOR = 'CLOSE_HEADLINE_EDITOR';
 export const OPEN_IMAGE_EDITOR = 'OPEN_IMAGE_EDITOR';
 export const CLOSE_IMAGE_EDITOR = 'CLOSE_IMAGE_EDITOR';